added link to home
yubodiwu/ReForum pull request #20
Opened 2021-01-14 09:01 UTC by XingyuLi20

2021-01-18 08:00 UTC, Eric-Le-Ge requested changes

2021-01-18 08:00 UTC, Eric-Le-Ge commented on frontend/Components/Header/Logo/styles.css
> +}
Nit - Could we add a new line here?

2021-01-29 04:05 UTC, Eric-Le-Ge approved these changes

2021-01-29 04:11 UTC, yubodiwu approved these changes

2021-01-29 04:11 UTC, merged